from app import app, db, Person

data = [
    ("Akshaya", "Q"),
    ("Anagha", "Q"),
    ("Cathrene", "Q"),
    ("Abhi Lavanya", "Q"),
    ("Harshika", "Q"),
    ("Muthu Vaishnavi", "Q"),
    ("Sharadha", "Q"),
    ("Nola Daisy", "Q"),
    ("Samyuctaa", "Q"),
    ("Krishnendu", "Q"),
    ("Pranisha", "Q"),
    ("Sahana", "Q"),
    ("Sreenithika", "Q"),
    ("Varnikha Shree", "Q"),
    ("Ishwarya", "Q"),
    ("Meenakshy", "Q"),
    ("Sreya Sriram", "Q"),
    ("Mirudula", "Q"),
    ("Kamalika", "Q"),
    ("Akshini", "Q"),
    ("Sujana", "Q"),
    ("Navya Sree", "Q"),
    ("Vishnupriya", "Q"),
    ("Nivedha", "Q"),
    ("Sivanipriya", "P"),
    ("Pavithra", "P"),
    ("Dharani Sengottuvelu", "P"),
    ("Aishwarya", "P"),
    ("Keerthanaa", "P"),
    ("Vasundaraa", "P"),
    ("Janya Pragya", "P"),
    ("Kiruthiga", "P"),
    ("Abinaya", "P"),
    ("Jothi Sri", "P"),
    ("Shreya Kathikeyan", "P"),
    ("Harini", "P"),
    ("Nandhana Prakash", "P"),
    ("Priyanka", "P"),
    ("Akshara", "P"),
    ("Abinaya Sowmya", "P"),
    ("Yuktanidhi", "P"),
    ("Prasitha", "P"),
    ("Keerthika", "P"),
    ("Naliniksha", "P"),
    ("Sushmitha", "P"),
    ("Roshini", "P"),
    ("Punitha", "P"),
    ("Shivaranjani (Pallavi)", "P"),
    ("Subha Geetha", "P"),
    ("Swastika", "P"),
    ("Shunmathi", "P"),
    ("Gaayathri", "P"),
    ("Sowmiya", "P"),
    ("Yuvapriya", "P"),
    ("Raseena Thasneem", "P"),
    ("Sulochana", "P"),
    ("Mamathishiya", "N"),
    ("Deepika", "N"),
    ("Ahalya", "N"),
    ("Sanjena", "N"),
    ("Madhubaalika", "N"),
    ("Renjitha", "N"),
    ("Ramyaa", "N"),
    ("Madhumitha", "N"),
    ("Dharshana", "N"),
    ("Vishruthi", "N"),
    ("Sangeetha", "N"),
    ("Ishwaryaa", "N"),
    ("Dhivya", "N"),
    ("Jane Princess", "N"),
    ("Sonali Shruthi", "N"),
    ("Devaabinaya", "N"),
    ("Nithisha", "N"),
    ("Sarashivasri", "N"),
    ("Samyuktha", "N"),
    ("VeniZha", "N"),
    ("Shrinidhi", "N"),
    ("Nandhini", "N"),
]

with app.app_context():
    db.create_all()
    for name, batch in data:
        db.session.add(Person(name=name, batch=batch))
        db.session.commit()

